### ISSUE TITLE
Issue related to NPC

### ISSUE THREAD

**Issue by Petrociaczhe** [thhoney08/ZombieHighMod#2]
- fireman npc mission use TALK_FIREMAN_JOB instead of TALK_MISSION_LIST like other npc.
- fireman npc offer archer npc mission instead of their own.
- hacker npc offer chairman npc zed killing mission due to the same mission id. after that, hacker npc give chairman npc mission.
- 1 hacker mission description ask for 4 mocro motor while the mission actually ask for 4 tiny motor.
- 2 same file for snowman with only job name and job description are different. give same talk option twice.

**Comment by thhoney08** [comment]
fixed, i think.

**Comment by Petrociaczhe** [comment]
~~the chairman and the hacker mission still have the same id (MISSION_SCHOOL_KILL_ROOFTOP_ZED).~~

~~the other four is fixed.~~

edit : all fixed

**Comment by thhoney08** [comment]
Finally fixed!!
